model:
  _name: ???
  hidden_dim: 256
dataset:
  _name: ???
  num_cl: 1
  augment: ???
  valid_split: 0.1
  transition_matrix: uniform
optimizer:
  lr: 1e-3
strategy:
  _name: ???
  type: ???
training:
  config_file: ???
  batch_size: 512
  epoch: 300
  valid_type: Accuracy
  eval_epoch: 1
  do_train: False
  do_predict: False
  log_step: 50
  seed: ???
  output_dir: ./